services:
  - type: web
    name: analytidata-backend
    env: python
    region: singapore
    plan: free
    pythonVersion: 3.10.13   # ✅ ADD THIS LINE
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DB_NAME
        value: analytidata
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://analytidata.vercel.app